config/routes.rb
Demo::Application.routes.draw do
  resources :vector_codes, :except=>[:new,:show, :edit,:create,:update,:destroy]  do
    collection do
      get "bot"
      get "bot_show"
    end
  end
  
  
  resources :spiders, :except=>[:new,:show, :edit,:create,:update,:destroy] do
    collection do
      get 'basic'
      get 'folder'
      get 'page'
      get 'custom'
    end
  end
  
  resources :uri_searchs, :except=>[:new,:show, :edit,:create,:update,:destroy]  do
    collection do
      get 'login_query'
      get 'keywords'
    end
  end

  resources :statuscodes, :except=>[:new,:show, :edit,:create,:update,:destroy]  do
    collection do
      get 'user'
      get 'spider'
    end
  end
  
  resources :labs, :except=>[:new,:show, :edit,:create,:update,:destroy]  do
    collection do
      get 'login_catch'
    end
  end
  
  resources :dashboards,:except=>[:new,:show, :edit,:create,:update,:destroy]  do

  end
  

end

app/models/nginxlog.rb
class Nginxlog < ActiveRecord::Base
  self.table_name = "nginx"
  
end

app/models/vector_code.rb
class VectorCode < Nginxlog
  # attr_accessible :title, :body
  
  default_scope ->{limit(200)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    date_start = 8.days.ago.strftime("%Y%m%d")
    date_end   = 1.days.ago.strftime("%Y%m%d")
    @data = Nginxlog.find_by_sql("select date, count(id) as ids from nginx where date >= #{date_start} and date <= #{date_end} group by date")
    @page_data = Nginxlog.find_by_sql("select date, count(id) as ids from nginx where date >= #{date_start} and date <= #{date_end} and is_page = 1 group by date")
    @asset_data = Nginxlog.find_by_sql("select date, count(id) as ids from nginx where date >= #{date_start} and date <= #{date_end} and is_page = 0 group by date")
  end
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController
end

app/controllers/spiders_controller.rb
class SpidersController < ApplicationController
  def basic
    date_start = 4.days.ago.strftime("%Y%m%d")
    date_end   = 1.days.ago.strftime("%Y%m%d")
    @data = Nginxlog.find_by_sql("select date, count(id) as ids from nginx where date >= #{date_start} and date <= #{date_end} and bot_agent is not null group by date")
    @page_data = Nginxlog.find_by_sql("select date, count(id) as ids from nginx where date >= #{date_start} and date <= #{date_end} and is_page = 1 and bot_agent is not null group by date")

  end
  
  def folder
    @date = params[:m_date] || 1.days.ago.strftime("%Y%m%d")
    @data = VectorCode.find_by_sql("select uri_sub,count(id) as ids from nginx where date=#{@date} and is_page =1 and bot_agent is not null group by uri_sub order by ids desc limit 20")
  end
  
  def page
    @date = params[:m_date] || 1.days.ago.strftime("%Y%m%d")
    @data = VectorCode.find_by_sql("select bot_agent, count(id) as ids from nginx where date = #{@date} and is_page = 1  and bot_agent is not null group by bot_agent order by ids desc")

  end
  
  def custom
    @date = params[:m_date] || 1.days.ago.strftime("%Y%m%d")
    @bots = VectorCode.find_by_sql("select bot_agent from nginx where date=#{@date} and bot_agent is not null and is_page = 1 group by bot_agent")
    if params[:agent]
      @data = Nginxlog.find_by_sql("select uri_sub, count(id) as ids from nginx where date = #{@date} and is_page =1 and bot_agent = '#{params[:agent]}' group by uri_sub order by ids desc limit 20")
    end
  end
end

app/controllers/statuscodes_controller.rb
class StatuscodesController < ApplicationController
  
  def index
    @date = params[:m_date] || 1.days.ago.strftime("%Y%m%d") 
    data = Nginxlog.find_by_sql("select count(id) as ids, code from nginx where date = #{@date} and bot_agent is not null group by code order by code")
    user_data = Nginxlog.find_by_sql("select count(id) as ids, code from nginx where date = #{@date} and bot_agent is null group by code order by code")
    codes = [] << data.map(&:code) << user_data.map(&:code)
    @codes = codes.flatten.uniq!
    @data = generate_hash(data)
    @user_data = generate_hash(user_data)
    
  end
  
  
  def generate_hash(datas)
    hash = {}
    datas.each do |item|
      hash[item.code] = item.ids
    end
    return hash
  end
  
end

app/controllers/uri_searchs_controller.rb
class UriSearchsController < ApplicationController
  def login_query
    date_start = 7.days.ago.strftime("%Y%m%d")
    date_end   = 1.days.ago.strftime("%Y%m%d")
    test_ip = '106.37.187.10'
    login_path = '/loginDex'
    @data = Nginxlog.find_by_sql("select date, count(id) as ids from nginx where date >= #{date_start} and date <= #{date_end} and uri_sub = '#{login_path}' and code = 200 group by date")
    @user_data = Nginxlog.find_by_sql("select date, count(id) as ids from nginx where date >= #{date_start} and date <= #{date_end} and uri_sub = '#{login_path}' and code = 200 and ip != '#{test_ip}' group by date")
  end
end

app/controllers/vector_codes_controller.rb
class VectorCodesController < ApplicationController
  # GET /vector_codes
  # GET /vector_codes.json
  def index
    @date = params[:m_date] || 1.days.ago.strftime("%Y%m%d")
    @vector_codes = VectorCode.find_by_sql("select count(ip) as ips, uri_sub, code from nginxlogs where date = #{@date} group by code order by ips desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vector_codes }
    end
  end
  
  def bot
    @date = 1.days.ago.strftime("%Y%m%d")
    @vector_codes = VectorCode.find_by_sql("select bot_agent, count(ip) as ips, uri_sub, code from nginxlogs where date = #{@date} and bot_agent is not null group by bot_agent order by ips desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vector_codes }
    end
  end
  
  
  def bot_show
    @date = 1.days.ago.strftime("%Y%m%d")
    @bot = params[:m_bot]
    @vector_codes = VectorCode.find_by_sql("select bot_agent, count(ip) as ips, uri_sub, code from nginxlogs where date = #{@date} and bot_agent ='#{@bot}' group by uri_sub order by ips desc")
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vector_codes }
    end
  end

  # GET /vector_codes/1
  # GET /vector_codes/1.json
  def show
    @vector_code = VectorCode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vector_code }
    end
  end

  # GET /vector_codes/new
  # GET /vector_codes/new.json
  def new
    @vector_code = VectorCode.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vector_code }
    end
  end

  # GET /vector_codes/1/edit
  def edit
    @vector_code = VectorCode.find(params[:id])
  end

  # POST /vector_codes
  # POST /vector_codes.json
  def create
    @vector_code = VectorCode.new(params[:vector_code])

    respond_to do |format|
      if @vector_code.save
        format.html { redirect_to @vector_code, notice: 'Vector code was successfully created.' }
        format.json { render json: @vector_code, status: :created, location: @vector_code }
      else
        format.html { render action: "new" }
        format.json { render json: @vector_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vector_codes/1
  # PUT /vector_codes/1.json
  def update
    @vector_code = VectorCode.find(params[:id])

    respond_to do |format|
      if @vector_code.update_attributes(params[:vector_code])
        format.html { redirect_to @vector_code, notice: 'Vector code was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vector_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vector_codes/1
  # DELETE /vector_codes/1.json
  def destroy
    @vector_code = VectorCode.find(params[:id])
    @vector_code.destroy

    respond_to do |format|
      format.html { redirect_to vector_codes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/helpers/sems_helper.rb
module SemsHelper
end

app/helpers/spiders_helper.rb
module SpidersHelper
end

app/helpers/statuscodes_helper.rb
module StatuscodesHelper
end

app/helpers/uri_searchs_helper.rb
module UriSearchsHelper
end

app/helpers/vector_codes_helper.rb
module VectorCodesHelper
end

app/views/dashboards/index.html.erb
<% content_for :head do %>
	<script type="text/javascript" src="/js/highcharts.js"></script>
	<script type="text/javascript" src="/js/exporting.js"></script>
<% end %>


<div id="container" style="width:1000px;height: 500px;position: absolute"></div>

		<script type="text/javascript">
$(function () {
        $('#container').highcharts({
            title: {
                text: '最近7天访问量',
                x: -20 //center
            },
            subtitle: {
                text: '',
                x: -20
            },
            xAxis: {
                categories: [<%= @data.map(&:date).join(',') %>]
            },
            yAxis: {
                title: {
                    text: '访问次数'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                valueSuffix: '次'
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0
            },
            series: [{
                name: '总访问',
                data: [<%= @data.map(&:ids).join(',') %>]
            },{
                name: '页面访问',
                data: [<%= @page_data.map(&:ids).join(',') %>]
            },{
                name: '资源访问',
                data: [<%= @asset_data.map(&:ids).join(',') %>]
            }]
        });
    });
    

		</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link rel="stylesheet" href="/css/jquery-ui.min.css" type="text/css" media="screen" title="no title" charset="utf-8">
  <link rel="stylesheet" href="/css/jquery-ui.theme.min.css" type="text/css" media="screen" title="no title" charset="utf-8">
  <script type="text/javascript" src="/js/jquery-ui.min.js">
  </script>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
	<div class="header"></div>
	<ul class="menus_left">
		<li> <%= link_to "Dashboard", dashboards_path %></li>
		<li> <%= link_to "蜘蛛分析", spiders_path %></li>
		<ul class="sub">
			<li><%= link_to "概要分析", basic_spiders_path%></li>
			<li><%= link_to "目录分析", folder_spiders_path %></li>
			<li><%= link_to "蜘蛛抓取量", page_spiders_path %></li>
			<li><%= link_to "自定义查询", custom_spiders_path %></li>
		</ul>
		<li> <%= link_to "路径分析", uri_searchs_path%></li>
		<ul class="sub">
			<li><%= link_to "登陆IP分析", login_query_uri_searchs_path %></li>
			<li><%= link_to "跳转来源分析",  basic_sems_path %></li>
		</ul>
		<li> <%= link_to "状态码分析", statuscodes_path %></li>
		<ul class="sub">
			<li><%= link_to "用户状态码", user_statuscodes_path %></li>
			<li><%= link_to "蜘蛛状态码",  spider_statuscodes_path %></li>
		</ul>
	</ul>
	<div class="content">
	<%= yield %>
	</div>
<script type="text/javascript">
	$(function(){
		var height = document.documentElement.clientHeight;
		$("div.content").attr('style', 'height:'+(height-80)+'px')
	})
</script>
</body>
</html>

app/views/spiders/basic.html.erb
<% content_for :head do %>
	<script type="text/javascript" src="/js/highcharts.js"></script>
	<script type="text/javascript" src="/js/exporting.js"></script>
<% end %>


<div id="container" style="width:1000px;height: 500px;position: absolute"></div>

		<script type="text/javascript">
$(function () {
        $('#container').highcharts({
            title: {
                text: '最近5天抓取量',
                x: -20 //center
            },
            subtitle: {
                text: '',
                x: -20
            },
            xAxis: {
                categories: [<%= @data.map(&:date).join(',') %>]
            },
            yAxis: {
                title: {
                    text: '抓取次数'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                valueSuffix: '次'
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0
            },
            series: [{
                name: '总抓取',
                data: [<%= @data.map(&:ids).join(',') %>]
            },{
                name: '页面抓取',
                data: [<%= @page_data.map(&:ids).join(',') %>]
            }]
        });
    });
    

		</script>

app/views/spiders/custom.html.erb
<% content_for :head do %>
	<script type="text/javascript" src="/js/highcharts.js"></script>
	<script type="text/javascript" src="/js/exporting.js"></script>
<% end %>

<p style="line-height:50px; border-bottom:1px dashed #ddd">
	<!-- <label for="date">查询日期</label> <input type="text" name="date" value="<%= @date%>" id="date"> -->
	<label for="agent" style="margin-right:10px;">蜘蛛</label>
	<select name="agent" id="agent" size="1">
		<option value=''>全部</option>
		<% if !@bots.blank? %>
		  <% for item in @bots %>
		    <option value="<%= item.bot_agent %>"><%= item.bot_agent %></option>
		  <% end %>
		<% else %>
		  
		<% end %>
		
		
	</select>
	
	<input type="button" name="submit" value="查询" id="submit" style="margin-left:15px;">
</p>

<div id="container" style="width:1000px;height: 500px;position: absolute"></div>



<script type="text/javascript">
$(function(){
	$("#date").datepicker({
		dateFormat: "yymmdd"
	})
	
	$("#submit").click(function(){
		var datestring = $("#date").val();
		var agent = $("#agent").val();
		var uri = "<%= custom_spiders_path %>"
		if (agent != "") {
			window.location = uri + "?agent="+ agent ;
		}else{
			window.location = uri;
		}
	})
})
	
</script>
<script type="text/javascript">
<% if params[:agent] %>
	$(function () {
        $('#container').highcharts({
            title: {
                text: '昨日<%= params[:agent] %>目录抓取量',
                x: -20 //center
            },
            subtitle: {
                text: '显示抓取数量最多的20个目录',
                x: -20
            },
            xAxis: {
                categories: ['<%=raw @data.map(&:uri_sub).join("','") %>'],
				labels: {
					rotation: -45,
					align: 'right'
				}
            },
            yAxis: {
                title: {
                    text: '抓取次数'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                valueSuffix: '次'
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0
            },
            series: [{
                name: '抓取量',
                data: [<%= @data.map(&:ids).join(',') %>]
            }]
        });
    });
	<% end %>
</script>

app/views/spiders/folder.html.erb
<% content_for :head do %>
	<script type="text/javascript" src="/js/highcharts.js"></script>
	<script type="text/javascript" src="/js/exporting.js"></script>
<% end %>


<div id="container" style="width:1000px;height: 500px;position: absolute"></div>

		<script type="text/javascript">
$(function () {
        $('#container').highcharts({
            title: {
                text: '昨日目录抓取量',
                x: -20 //center
            },
            subtitle: {
                text: '显示抓取数量最多的20个目录',
                x: -20
            },
            xAxis: {
                categories: ['<%=raw @data.map(&:uri_sub).join("','") %>'],
				labels: {
					rotation: -45,
					align: 'right'
				}
            },
            yAxis: {
                title: {
                    text: '抓取次数'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                valueSuffix: '次'
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0
            },
            series: [{
                name: '抓取量',
                data: [<%= @data.map(&:ids).join(',') %>]
            }]
        });
    });
    

		</script>

app/views/spiders/page.html.erb
<% content_for :head do %>
	<script type="text/javascript" src="/js/highcharts.js"></script>
	<script type="text/javascript" src="/js/exporting.js"></script>
<% end %>


<div id="container" style="width:1000px;height: 500px;position: absolute"></div>

		<script type="text/javascript">
$(function () {
        $('#container').highcharts({
            title: {
                text: '不同蜘蛛抓取量',
                x: -20 //center
            },
            subtitle: {
                text: '显示抓取数量最多的20种蜘蛛',
                x: -20
            },
            xAxis: {
                categories: ['<%=raw @data.map(&:bot_agent).join("','") %>'],
				labels: {
					rotation: -45,
					align: 'right'
				}
            },
            yAxis: {
                title: {
                    text: '抓取次数'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                valueSuffix: '次'
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0
            },
            series: [{
                name: '抓取量',
                data: [<%= @data.map(&:ids).join(',') %>]
            }]
        });
    });
    

		</script>

app/views/statuscodes/index.html.erb
<% content_for :head do %>
	<script type="text/javascript" src="/js/highcharts.js"></script>
	<script type="text/javascript" src="/js/exporting.js"></script>
<% end %>


<div id="container" style="width:1000px;height: 500px;position: absolute"></div>

		<script type="text/javascript">
$(function () {
        $('#container').highcharts({
            title: {
                text: '请求状态统计',
                x: -20 //center
            },
            subtitle: {
                text: '',
                x: -20
            },
            xAxis: {
                categories: [<%=@codes.join(',') %>],
				labels: {
					rotation: -45,
					align: 'right'
				}
            },
            yAxis: {
                title: {
                    text: '抓取次数'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                valueSuffix: '次'
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0
            },
            series: [{
                name: '蜘蛛请求数量',
                data: [<%= @codes.inject([]){|y,x| y<< (@data[x] ?  @data[x] : 0) }.join(',') %>]
            },{
                name: '非蜘蛛请求数量',
                data: [<%= @codes.inject([]){|y,x| y<< (@user_data[x] ? @user_data[x] : 0)}.join(',')  %>]
            }]
        });
    });
    

		</script>

app/views/uri_searchs/login_query.html.erb
<% content_for :head do %>
	<script type="text/javascript" src="/js/highcharts.js"></script>
	<script type="text/javascript" src="/js/exporting.js"></script>
<% end %>


<div id="container" style="width:1000px;height: 500px;position: absolute"></div>

		<script type="text/javascript">
$(function () {
        $('#container').highcharts({
            title: {
                text: '最近7天IP登陆情况统计',
                x: -20 //center
            },
            subtitle: {
                text: '',
                x: -20
            },
            xAxis: {
                categories: [<%= @data.map(&:date).join(',') %>]
            },
            yAxis: {
                title: {
                    text: '登陆次数'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                valueSuffix: '次'
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0
            },
            series: [{
                name: '总登陆次数',
                data: [<%= @data.map(&:ids).join(',') %>]
            },{
                name: '客户登陆次数',
                data: [<%= @user_data.map(&:ids).join(',')  %>]
            }]
        });
    });
    

		</script>

app/views/vector_codes/_form.html.erb
<%= form_for(@vector_code) do |f| %>
  <% if @vector_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vector_code.errors.count, "error") %> prohibited this vector_code from being saved:</h2>

      <ul>
      <% @vector_code.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vector_codes/bot.html.erb
<h1>bot查询 日期: <%= @date%></h1>

<table>
  <tr>
    <th align="left">日期</th>
    <th align="left">访问次数</th>
    <th align="left">uri目录</th>
	<th align="left">状态码</th>
	<!-- <th></th> -->
  </tr>

<% @vector_codes.each do |vector_code| %>
  <tr>
    <td><%=link_to vector_code.bot_agent, bot_show_vector_codes_path(:m_bot=>vector_code.bot_agent) %></td>
    <td><%= vector_code.ips %></td>
    <td><%= vector_code.uri_sub %></td>
	<td><%= vector_code.code %></td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vector code', new_vector_code_path %>

app/views/vector_codes/bot_show.html.erb
<h1>状态码查询 日期: <%= @date%> UA: <%=@bot%></h1>

<table>
  <tr>
    <th align="left">日期</th>
    <th align="left">访问次数</th>
    <th align="left">uri目录</th>
	<th align="left">状态码</th>
	<!-- <th></th> -->
  </tr>

<% @vector_codes.each do |vector_code| %>
  <tr>
    <td><%#= vector_code.date %></td>
    <td><%= vector_code.ips %></td>
    <td><%= vector_code.uri_sub %></td>
	<td><%= vector_code.code %></td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vector code', new_vector_code_path %>

app/views/vector_codes/edit.html.erb
<h1>Editing vector_code</h1>

<%= render 'form' %>

<%= link_to 'Show', @vector_code %> |
<%= link_to 'Back', vector_codes_path %>

app/views/vector_codes/index.html.erb
<h1>状态码查询 日期: <%= @date%></h1>
<p>
	<label for="date">查询日期</label><input type="text" name="date" value="" id="date">
	<input type="button" name="submit" value="查询" id="submit">
</p>
<table>
  <tr>
    <th align="left">日期</th>
    <th align="left">访问次数</th>
    <th align="left">uri目录</th>
	<th align="left">状态码</th>
	<!-- <th></th> -->
  </tr>

<% @vector_codes.each do |vector_code| %>
  <tr>
    <td><%#= vector_code.date %></td>
    <td><%= vector_code.ips %></td>
    <td><%= vector_code.uri_sub %></td>
	<td><%= vector_code.code %></td>

  </tr>
<% end %>
</table>

<br />
<script type="text/javascript">
$(function(){
	$("#date").datepicker({
		dateFormat: "yymmdd"
	})
	
	$("#submit").click(function(){
		var datestring = $("#date").val();
		if (datestring.match(/201[4|5][0|1]\d[0-3]\d/)){
			var uri = "<%= basic_spiders_path %>"
			window.location = uri + "?m_date="+ datestring;
		}else{
			alert("请选择日期");
		}
	})
})
	
</script>

app/views/vector_codes/new.html.erb
<h1>New vector_code</h1>

<%= render 'form' %>

<%= link_to 'Back', vector_codes_path %>

app/views/vector_codes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_vector_code_path(@vector_code) %> |
<%= link_to 'Back', vector_codes_path %>